language: go

go:
  - 1.4

# I know I like my dependencies specified by custom meta tags in HTML!
# Oh wait, no. No I don't.
install: true

script:
  - ./goad init
  - ./goad validate
  - ./goad install
  - sudo bash -c "export PATH=$PATH ; export GOROOT=$GOROOT ; ./goad test" # unescaped dollars are eval'd in an implicit first shell
